---
title: "Pepe Vignette"
author: "Seyma Kalay"
data: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Pepe Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(pepe)
```


This package was set for the data visualization. 
First thing let's see the str of the *sample_data* with `str(sample_data)`. 

`Plot.by.Factr` function will create plotting.

```{r plot ,  fig.width= 7, echo=TRUE}
df <- sample_data[c("Formal","Informal","L.Both","No.Loan",
"sex","educ","political.afl","married",
 "havejob","rural","age","Income","Networth","Liquid.Assets",
 "NW.HE","fin.knowldge","fin.intermdiaries")]
 CN = colnames(df)
 var <- c("educ","rural","sex","havejob","political.afl")
 name.levels = c("Formal","Informal","L.Both","No.Loan",
 "sex","educ","political.afl","married",
 "havejob","rural","age","Income","Networth","Liquid.Assets",
 "NW.HE","fin.knowldge","fin.intermdiaries")
Plot.by.Factr(df4.Plot.by.Factr(var,df)$Summ.Stats.long, name.levels)
```


`df4.Plot.by.Factr` function will create group stats.

```{r df4plot, echo=TRUE}
df4.Plot.by.Factr(var,df)

```

`Stats.by.Factr` function will create group stats.

```{r statsfactr, echo=TRUE}
 Stats.by.Factr(var, df)
```



`Pvot.by.Factr` function will create a percentage tables.

```{r pivot, echo=TRUE}
library(dplyr)
head(sample_data)
sample_data$X <- 1
dscriptve <- as.data.frame(sample_data %>%
                             select(X, sex, married, havejob, educ, political.afl, rural,region,
                                    multi.level, Formal, Informal, L.Both, No.Loan))
colnames(dscriptve) <- c("X", "Gender", "Married", "Employed", "Education", "Party", "HR", "Region",
                         "Access Loan", "Formal", "Informal", "L.Both", "No.Loan")

dscriptve[] <- lapply(dscriptve[], factor); names(dscriptve)


name.df <- Pvot.by.Factr(dscriptve)[, c(1,2)]
df <- round(as.data.frame(lapply(Pvot.by.Factr(dscriptve)[,-c(1,2)], function(x) x*100)),2); df
df <- as.data.frame(lapply(df, function(x) paste0(x,'%'))); df
Pvot.by.Factr <- cbind(name.df, df); head(Pvot.by.Factr,20)
Pvot.by.Factr <- subset(Pvot.by.Factr, select = -c(X)); Pvot.by.Factr

```
